logging:
  level:
    root: info
    com:
      alencion:
        blog: debug

alencion:
  blog:
    post:
      #      resource-path: /Users/jeongjunlee/blog/application/src/main/resources/posts
      resource-path: E:/Projects/blog/application/src/main/resources/posts
